version: '3'

services:
  api:
    container_name: api
    build: ./api
    env_file:
      - .env
    environment:
      WAIT_HOSTS: mariadb:3306
    depends_on:
      - mariadb
    ports:
      - 3000:3000

  mariadb:
    image: mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger:/src/tmp
    ports:
      - 8080:8080
    environment:
      - SWAGGER_JSON=/src/tmp/swagger.yml

volumes:
  db:
