version: '3'

services:
  api:
    container_name: api
    build:
      dockerfile: ./api/Dockerfile
      context: .
    ports:
      - 3000:3000

  mariadb:
    image: mariadb
    env_file:
      - ./.env
    volumes:
      - are_you_hitler:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  are_you_hitler:
