version: '3'

services:
  api:
    container_name: api
    build:
      dockerfile: ./api/Dockerfile
      context: .
    volumes:
      - ./api:/app

  mariadb:
    image: mariadb
    env_file:
      - ./.env
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - 3306:3306
