version: '3'

services:
  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    volumes:
      - .:/src/tmp
    ports:
      - 8080:8080
    environment:
      - SWAGGER_JSON=/src/tmp/swagger.yml
