swagger: '2.0'
info:
  description: Are You Hitler? Is a web application designed to track games of 'Secret Hitler' and display user statistics.
  version: 1.0.0
  title: Are You Hitler?
  contact:
    email: jordansimsmith@gmail.com
  license:
    name: GNU General Public License v3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html

basePath: /api/v1
tags:
  - name: user
    description: Operations on users
  - name: game
    description: Operations on games

schemes:
  - https

paths:
  /users:
    post:
      tags:
        - user
      summary: Register a new user
      operationId: createUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User object to be registered
          required: true
          schema:
            $ref: '#/definitions/NewUser'
      responses:
        201:
          description: Created
          headers:
            Location:
              type: string
              description: Location of the newly created user
          schema:
            type: object
            properties:
              user_id:
                type: number
        400:
          description: Bad Request
        500:
          description: Internal Server Error

    get:
      tags:
        - user
      summary: List all users
      operationId: readUsers
      produces:
        - application/json
      parameters:
        - in: query
          name: first_name
          description: Search for users with this first name
          required: false
          type: string
        - in: query
          name: last_name
          description: Search for users with this last name
          required: false
          type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        500:
          description: Internal Server Error

  /users/{user_id}:
    get:
      tags:
        - user
      summary: Find a user by ID
      operationId: readUser
      produces:
        - application/json
      parameters:
        - in: path
          name: user_id
          description: ID of the user to find
          required: true
          type: number
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/User'
        404:
          description: Not Found
        500:
          description: Internal Server Error

    put:
      tags:
        - user
      summary: Update a user
      operationId: updateUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: user_id
          description: ID of the user to update
          required: true
          type: number
        - in: body
          name: body
          description: Updated user details
          required: true
          schema:
            $ref: '#/definitions/NewUser'
      responses:
        204:
          description: No Content
        404:
          description: Not Found
        500:
          description: Internal Server Error

    delete:
      tags:
        - user
      summary: Delete a user
      operationId: deleteUser
      produces:
        - application/json
      parameters:
        - in: path
          name: user_id
          description: ID of the user to delete
          required: true
          type: number
      responses:
        204:
          description: No Content
        404:
          description: Not Found
        500:
          description: Internal Server Error

  /games:
    post:
      tags:
        - game
      summary: Register a new game
      operationId: createGame
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Game object to be registered
          required: true
          schema:
            $ref: '#/definitions/NewGame'
      responses:
        201:
          description: Created
          headers:
            Location:
              type: string
              description: Location of the newly created game
          schema:
            type: object
            properties:
              game_id:
                type: number
        400:
          description: Bad Request
        500:
          description: Internal Server Error

    get:
      tags:
        - game
      summary: List all games
      operationId: readGames
      produces:
        - application/json
      parameters:
        - in: query
          name: user_id
          description: Search for games where this user played
          required: false
          type: string
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Game'
        404:
          description: Not Found
        500:
          description: Internal Server Error

  /games/{game_id}:
    get:
      tags:
        - game
      summary: Find a game by ID 
      operationId: readGame 
      produces: 
        - application/json
      parameters:
        - in: path
          name: game_id
          description: ID of the game to find
          required: true
          type: number
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Game'
        404:
          description: Not Found
        500:
          description: Internal Server Error

    put:
      tags:
        - game
      summary: Update a game
      operationId: updateGame
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: game_id
          description: ID of the game to update
          required: true
          type: number
        - in: body
          name: body
          description: Updated game details
          required: true
          schema:
            $ref: '#/definitions/NewGame'
      responses:
        204:
          description: No Content
        404:
          description: Not Found
        500:
          description: Internal Server Error

    delete:
      tags:
        - game
      summary: Delete a game
      operationId: deleteGame
      produces:
        - application/json
      parameters:
        - in: path
          name: game_id
          description: ID of the game to delete
          required: true
          type: number
      responses:
        204:
          description: No Content
        404: 
          description: Not Found 
        500:
          description: Internal Server Error

definitions:
  NewUser:
    type: object
    properties:
      first_name:
        type: string
        example: Joseph
      last_name:
        type: string
        example: Stalin

  User:
    allOf:
      - type: object
        properties:
          user_id:
            type: number
            example: 1
      - $ref: '#/definitions/NewUser'

  NewGame: 
    type: object
    properties:
      timestamp:
        type: number
        description: UNIX timestamp (seconds past Epoch)
        example: 1561681534
      winner: 
        type: string
        description: Either 'fascist' or 'liberal'
        example: 'facist'
      number_of_players:
        type: number
        example: 1
      players:
        type: array
        items:
          $ref: '#/definitions/Player'

  Game:
    allOf:
      - type: object
        properties:
          game_id:
            type: number
      - $ref: '#/definitions/NewGame'

  Player:
    type: object
    properties:
      user_id:
        type: string
        example: 1
      faction:
        type: string
        description: Either 'fascist' or 'liberal'
        example: 'fascist'
      hitler:
        type: boolean
        desription: Was this player hitler?
        example: true
